### ISSUE TITLE
Add support for installation of plugin from remote git repository

### ISSUE THREAD

**Issue by KrazyKirby99999** [SteamDeckHomebrew/PluginLoader#40]
It would be useful for installation and updating if users could simply enter a url to a github or gitlab repository to install a plugin.

**Comment by milroneth** [comment]
Based on Discord discussion on this, I like the idea of the URL bar. Would work by providing a GitHub repo URL which it will `git clone`.

Since devs asked for specific branches too, the easy way to implement without adding selector menus, having to read branches form the site, etc. would be to provide the branch URL directly, then the loader would just have to split the string and run a couple extra commands, scaffold code would look like:

Input: `https://github.com/DevName/PluginName/tree/branchName`
```sh
git clone $input
if $branchName {
  cd $PluginName
  git checkout $branchName
}
```
Sounds quick and easy, without much complexity.

**Comment by Wolvan** [comment]
Addition to @milroneth's comment, which I am very much in favor of by the way:
You can directly check out a specific branch during cloning by providing git with the `-b <branch-name>` parameter during clone, no additional checkout needed.
(Example: `git clone -b dev https://github.com/Wolvan/spdck.git /home/deck/homebrew/plugins/spdck`)

**Comment by JohnnyCrazy** [comment]
Not sure how this aligns with our idea of react plugins.

As soon as we ship react-based plugins, all plugins will have some kind of build step involved, converting JSX/TSX to JS and bundling all other possible dependencies. Since you normally don't want to store these "build" artifacts in the repo itself, branches are not *runnable* by default.

**Comment by TrainDoctor** [comment]
> Not sure how this aligns with our idea of react plugins.
> 
> As soon as we ship react-based plugins, all plugins will have some kind of build step involved, converting JSX/TSX to JS and bundling all other possible dependencies. Since you normally don't want to store these "build" artifacts in the repo itself, branches are not _runnable_ by default.

I have to agree unfortunately. I think we should move this to a URL that will support different repositories releases as already compiled code/binaries as the way to address this problem.

**Comment by TrainDoctor** [comment]
Zip files from URL are now supported in react-frontend-plugins branch.
