### ISSUE TITLE
Wrong permissions on the homebrew folder

### ISSUE THREAD

**Issue by LiamDawe** [SteamDeckHomebrew/PluginLoader#71]
Hi, by default the homebrew folder and subfolders in /home/ only has the ability to view content.

This needs to be adjusted so the user can actually interact with them, and put the plugins into the folder.

**Comment by NGnius** [comment]
Allowing any program (including user-run programs) to modify those files is a security risk because it can allow regular plugins to escalate their privileges to root.
That's why the official method to install plugins is through the plugin store, since it avoids this limitation. Any other method to install plugins should only be done by developers (and/or people comfortable using `sudo`)

**Comment by LiamDawe** [comment]
Ah I see okay, that makes sense, I haven't used it for a while :)
